// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9RmLbDzHeZk7J_-JHG1DcAeGYkxjkI3Y',
    appId: '1:659543137345:web:9e619a41d6b4ae19f53ac0',
    messagingSenderId: '659543137345',
    projectId: 'la-classroom',
    authDomain: 'la-classroom.firebaseapp.com',
    storageBucket: 'la-classroom.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuzBzHG9xTiArHi1Qccnh4TjRfGr75yYo',
    appId: '1:659543137345:android:b69c5d7497ab2177f53ac0',
    messagingSenderId: '659543137345',
    projectId: 'la-classroom',
    storageBucket: 'la-classroom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4xbqtz-wDs9kLrXVRdHN-eSW2zCfOWT4',
    appId: '1:659543137345:ios:60b886a98998b8f3f53ac0',
    messagingSenderId: '659543137345',
    projectId: 'la-classroom',
    storageBucket: 'la-classroom.appspot.com',
    iosClientId: '659543137345-skr0rjkgfhod441h0if46vbjgs9r958g.apps.googleusercontent.com',
    iosBundleId: 'com.example.laclassroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4xbqtz-wDs9kLrXVRdHN-eSW2zCfOWT4',
    appId: '1:659543137345:ios:60b886a98998b8f3f53ac0',
    messagingSenderId: '659543137345',
    projectId: 'la-classroom',
    storageBucket: 'la-classroom.appspot.com',
    iosClientId: '659543137345-skr0rjkgfhod441h0if46vbjgs9r958g.apps.googleusercontent.com',
    iosBundleId: 'com.example.laclassroom',
  );
}
